id = "kairos"
name = "Kairos"
description = "The open source coding agent."
version = "1.14.30"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/kairos"

[agent_servers.kairos]
name = "Kairos"
icon = "./icons/kairos.svg"

[agent_servers.kairos.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/kairos/releases/download/v1.14.30/kairos-darwin-arm64.zip"
cmd = "./kairos"
args = ["acp"]

[agent_servers.kairos.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/kairos/releases/download/v1.14.30/kairos-darwin-x64.zip"
cmd = "./kairos"
args = ["acp"]

[agent_servers.kairos.targets.linux-aarch64]
archive = "https://github.com/anomalyco/kairos/releases/download/v1.14.30/kairos-linux-arm64.tar.gz"
cmd = "./kairos"
args = ["acp"]

[agent_servers.kairos.targets.linux-x86_64]
archive = "https://github.com/anomalyco/kairos/releases/download/v1.14.30/kairos-linux-x64.tar.gz"
cmd = "./kairos"
args = ["acp"]

[agent_servers.kairos.targets.windows-x86_64]
archive = "https://github.com/anomalyco/kairos/releases/download/v1.14.30/kairos-windows-x64.zip"
cmd = "./kairos.exe"
args = ["acp"]
