import Foundation

// Stable identifier used for both the macOS LaunchAgent label and Nix-managed defaults suite.
// nix-kairos writes app defaults into this suite to survive app bundle identifier churn.
let launchdLabel = "ai.kairos.mac"
let gatewayLaunchdLabel = "ai.kairos.gateway"
let onboardingVersionKey = "kairos.onboardingVersion"
let onboardingSeenKey = "kairos.onboardingSeen"
let currentOnboardingVersion = 7
let pauseDefaultsKey = "kairos.pauseEnabled"
let iconAnimationsEnabledKey = "kairos.iconAnimationsEnabled"
let swabbleEnabledKey = "kairos.swabbleEnabled"
let swabbleTriggersKey = "kairos.swabbleTriggers"
let voiceWakeTriggerChimeKey = "kairos.voiceWakeTriggerChime"
let voiceWakeSendChimeKey = "kairos.voiceWakeSendChime"
let showDockIconKey = "kairos.showDockIcon"
let defaultVoiceWakeTriggers = ["kairos"]
let voiceWakeMaxWords = 32
let voiceWakeMaxWordLength = 64
let voiceWakeMicKey = "kairos.voiceWakeMicID"
let voiceWakeMicNameKey = "kairos.voiceWakeMicName"
let voiceWakeLocaleKey = "kairos.voiceWakeLocaleID"
let voiceWakeAdditionalLocalesKey = "kairos.voiceWakeAdditionalLocaleIDs"
let voicePushToTalkEnabledKey = "kairos.voicePushToTalkEnabled"
let voiceWakeTriggersTalkModeKey = "kairos.voiceWakeTriggersTalkMode"
let talkEnabledKey = "kairos.talkEnabled"
let talkPhaseSoundsEnabledKey = "kairos.talkPhaseSoundsEnabled"
let talkShiftToStopEnabledKey = "kairos.talkShiftToStopEnabled"
let iconOverrideKey = "kairos.iconOverride"
let connectionModeKey = "kairos.connectionMode"
let remoteTargetKey = "kairos.remoteTarget"
let remoteIdentityKey = "kairos.remoteIdentity"
let remoteProjectRootKey = "kairos.remoteProjectRoot"
let remoteCliPathKey = "kairos.remoteCliPath"
let canvasEnabledKey = "kairos.canvasEnabled"
let cameraEnabledKey = "kairos.cameraEnabled"
let systemRunPolicyKey = "kairos.systemRunPolicy"
let systemRunAllowlistKey = "kairos.systemRunAllowlist"
let systemRunEnabledKey = "kairos.systemRunEnabled"
let locationModeKey = "kairos.locationMode"
let locationPreciseKey = "kairos.locationPreciseEnabled"
let peekabooBridgeEnabledKey = "kairos.peekabooBridgeEnabled"
let deepLinkKeyKey = "kairos.deepLinkKey"
let modelCatalogPathKey = "kairos.modelCatalogPath"
let modelCatalogReloadKey = "kairos.modelCatalogReload"
let cliInstallPromptedVersionKey = "kairos.cliInstallPromptedVersion"
let heartbeatsEnabledKey = "kairos.heartbeatsEnabled"
let debugPaneEnabledKey = "kairos.debugPaneEnabled"
let debugFileLogEnabledKey = "kairos.debug.fileLogEnabled"
let appLogLevelKey = "kairos.debug.appLogLevel"
let voiceWakeSupported: Bool = ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 26
