export const browserCoreExamples = [
  "kairos browser status",
  "kairos browser start",
  "kairos browser start --headless",
  "kairos browser stop",
  "kairos browser tabs",
  "kairos browser open https://example.com",
  "kairos browser focus abcd1234",
  "kairos browser close abcd1234",
  "kairos browser screenshot",
  "kairos browser screenshot --full-page",
  "kairos browser screenshot --ref 12",
  "kairos browser snapshot",
  "kairos browser snapshot --format aria --limit 200",
  "kairos browser snapshot --efficient",
  "kairos browser snapshot --labels",
];

export const browserActionExamples = [
  "kairos browser navigate https://example.com",
  "kairos browser resize 1280 720",
  "kairos browser click 12 --double",
  "kairos browser click-coords 120 340",
  'kairos browser type 23 "hello" --submit',
  "kairos browser press Enter",
  "kairos browser hover 44",
  "kairos browser drag 10 11",
  "kairos browser select 9 OptionA OptionB",
  "kairos browser upload /tmp/kairos/uploads/file.pdf",
  'kairos browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "kairos browser dialog --accept",
  'kairos browser wait --text "Done"',
  "kairos browser evaluate --fn '(el) => el.textContent' --ref 7",
  "kairos browser console --level error",
  "kairos browser pdf",
];
