name: kairos

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  kairos:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /kairos') ||
      startsWith(github.event.comment.body, '/kairos')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run kairos
        uses: anomalyco/kairos/github@latest
        env:
          kairos_API_KEY: ${{ secrets.kairos_API_KEY }}
          kairos_PERMISSION: '{"bash": "deny"}'
        with:
          model: kairos/kairos-apple-4-5
